### ISSUE TITLE
Subscriptions on root isn't shown.

### ISSUE THREAD

**Issue by yayugu** [azu/irodr#60]
I found Irodr only shown subscriptions which contained by some folders.
It seems a bug or unkind behavior.

すばらしいプロダクトをありがとうございます
感動しながら使い始めています！:heart:

**Comment by azu** [comment]
Thanks for report.
It seem a bug.

This line just ignore a subscription that has not categories(empty categories).
https://github.com/azu/irodr/blob/de3de35b3fef98eb22e84900fa296b86718c6386/src/infra/repository/SubscriptionRepository.ts#L38
We will fix this bug.

**Comment by azu** [comment]
Probably, I fix this issue by #61 
![image](https://user-images.githubusercontent.com/19714/46259473-f7ab0c00-c514-11e8-83dd-8ff74a8bbde2.png)

**Comment by yayugu** [comment]
Thanks for rapid fix!
I'll check when deployed to https://irodr.netlify.com

**Comment by azu** [comment]
I've commited a bug fix and deploy it https://github.com/azu/irodr/commit/6d5863e98ba359996209a057c0bd9edf063f3252

It work in my enviroments.
Can you try to reload again?

![image](https://user-images.githubusercontent.com/19714/46275303-67fa7180-c597-11e8-9547-74efcd36f2bf.png)

![image](https://user-images.githubusercontent.com/19714/46275288-5a44ec00-c597-11e8-8ec3-9757a306d7b9.png)

**Comment by yayugu** [comment]
Works perfectly!!
