### ISSUE TITLE
何も表示されません

### ISSUE THREAD

**Issue by aetos382** [azu/irodr#63]
頭悪いタイトルですいません。

右上に「Unreads」と「Subscriptions」の数字は出ますが、それ以外は何も表示されません。
画面はこんな感じです。

https://twitter.com/aetos382/status/1046629890403921922

API のレスポンスはこちらです。

https://gist.github.com/aetos382/71dc9b60b2fd66a56a7d13d7b357e973

**Comment by aetos382** [comment]
追記：InoReader は有料の Plus プランを使用しています。

**Comment by azu** [comment]
https://github.com/azu/irodr/tree/master/src/use-case/subscription/ci の代わりにローカルで貼ってもらったデータを読み込んで見たら、一応次の2つが表示されたました。
![image](https://user-images.githubusercontent.com/19714/46275858-4dc19300-c599-11e8-9baa-5761028a780f.png)
レスポンスデータを見た感じ他はすべて既読なのであってそうな気がします。

ついさっき #60 でカテゴリが設定されてないフィードが表示されない問題を修正したので、もう一度リロードしてみたら表示が変わったりしてないですかね?

**Comment by aetos382** [comment]
その問題がついさっき修正されたばかりなら、それかもしれません。

Chrome のアドインのせいかと思って全部オフにしたら表示されました。
また、一切アドインを入れていないプレーンな Firefox でも表示されました。

その後、悪さをしているアドインを特定すべく、１つずつ有効にしていったのですが、問題が起きていた当時に有効だったものをすべて再度有効にしても、問題が再現しなくなってしまいました（現在はリストが表示されている状態です）。

アドインは関係なく、タイミングの問題かもしれません。
